### ISSUE TITLE
Experiment results on qm9 dataset

### ISSUE THREAD

**Issue by ndkhanh360** [vgsatorras/egnn#10]
Dear author,

I am trying to reproduce the results on the qm9 dataset in Table 3 but encounter something that I don't really understand. Specifically, when I ran your code, I achieved a very low MAE on the chemical property U_0 (train MAE ~ 0.001, test MAE ~ 0.011 - much lower than the test result 11 in the paper), which makes me think that the unit used in the code is eV instead of meV as reported in the paper. Can you help me confirm if what I think is true or not?

Another thing is that for the chemical property ZPVE, the test MAE was much higher than the train MAE (about 0.002 for train vs 1.61 for test - but this number is pretty close to the test result 1.55 in the paper), which confuses me about the unit used in the code for this property (I guess it is meV, not eV as in the above case). It would be great if you can provide more details with regard to this situation.

Thank you :)
Khanh Nguyen.

**Comment by vgsatorras** [comment]
As you mentioned, the metric used in the code for U_0 is eV while in the paper it was reported in meV for better readability. The same happens for other properties like ZPVE.

Best,
Victor
